name: Deploy
on:
  push:
    tags:
      - '*'       
jobs:
  deploy_web_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          node-version: '17.0.1'

    - name: Install Agular
      run: npm install -g @vue/cli@5.0.0-rc.2 @vue/cli-service-global@5.0.0-rc.2
        
    - name: Install dependencies
      run: npm install

    - name: Build web
      run: ng build --base-href /$BASE_HREF/ --deploy-url /$BASE_HREF/
      env:
        BASE_HREF: ${{ github.event.repository.name }}
        
    - name: Deploy to Github page
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-page
        FOLDER: dist/web
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MESSAGE: "🚀 deploy commit {sha} "
