name: Deploy
on:
  push:
    branches:
      - main
      
jobs:
  deploy_web_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          node-version: '20.4.0'
    - uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false
        
    - name: Install dependencies
      run: pnpm i

    - name: Build web
      run: pnpm build_gh
      # env:
      #   BASE_HREF: /${{ github.event.repository.name }}/
        
    - name: Deploy to Github page
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-page
        FOLDER: dist
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MESSAGE: "🚀 deploy commit {sha} "
