name: Deploy
on:
  push:
    branches:
      - main
      
jobs:
  deploy_web_app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          node-version: '17.0.1'

    - name: Install Agular
      run: npm install -g @vue/cli@next @vue/cli-service-global@next
        
    - name: Install dependencies
      run: npm install

    - name: Build web
      run: npm run build
      env:
        BASE_HREF: ${{ github.event.repository.name }}
        
    - name: Deploy to Github page
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-page
        FOLDER: dist
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MESSAGE: "🚀 deploy commit {sha} "
